# Generated by Django 4.2.5 on 2023-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='job_title',
            field=models.CharField(choices=[('A', 'Accountant'), ('D', 'Software developer'), ('T', 'Software tester'), ('M', 'Manager')], max_length=256),
        ),
    ]
