# Generated by Django 4.2.5 on 2023-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_alter_employeemodel_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='jobTitle',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('software developer', 'Software developer'), ('software tester', 'Software tester'), ('manager', 'Manager')], default='', max_length=256),
        ),
    ]
