# Generated by Django 4.2.5 on 2023-09-17 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_remove_employeemodel_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
